server:
  port: 8081

dubbo:
  scan:
    # 指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.tuling.mall.user.service
  #  application:
  #    name: ${spring.application.name}
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
#  registry:
#    #挂载到 Spring Cloud 注册中心  高版本可选
#    address: spring-cloud://127.0.0.1:8848

spring:
  application:
    name: spring-cloud-dubbo-provider-user-feign-sentinel
  main:
    # Spring Boot2.1及更高的版本需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: 127.0.0.1:8080
      datasource:
        flow-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP   # 注意groupId对应Sentinel Dashboard中的定义
            data-type: json
            rule-type: flow
          degrade-rules:
            nacos:
              server-addr: 127.0.0.1:8848
              dataId: ${spring.application.name}-degrade-rules
              groupId: SENTINEL_GROUP
              data-type: json
              rule-type: degrade
          param-flow-rules:
            nacos:
              server-addr: 127.0.0.1:8848
              dataId: ${spring.application.name}-param-flow-rules
              groupId: SENTINEL_GROUP
              data-type: json
              rule-type: param-flow
          authority-rules:
            nacos:
              server-addr: 127.0.0.1:8848
              dataId: ${spring.application.name}-authority-rules
              groupId: SENTINEL_GROUP
              data-type: json
              rule-type: authority

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root

#暴露actuator端点   http://localhost:8800/actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'
