server:
  port: 8055

spring:
  application:
    name: mall-user-feign-demo  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


ribbon:
  eager-load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置mall-user使用ribbon饥饿加载，多个使用逗号分隔
    clients: mall-order


logging:
  level:
    com.tuling.mall.feigndemo.feign: debug

feign:
#  client:
#    config:
#      mall-order:  #对应微服务
#        loggerLevel: FULL
        #contract: feign.Contract.Default   #指定Feign原生注解契约配置
#        requestInterceptors[0]:  #配置拦截器
#          com.tuling.mall.feigndemo.interceptor.FeignAuthRequestInterceptor
        # 连接超时时间，默认2s
#        connectTimeout: 3000
        # 请求处理超时时间，默认5s
#        readTimeout: 10000
        # 配置编解码器
#        encoder: feign.jackson.JacksonEncoder
#        decoder: feign.jackson.JacksonDecoder

  #feign 使用 okhttp
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
  # 配置 GZIP 来压缩数据
  compression:
    request:
      enabled: true
      # 配置压缩的类型
      mime-types: text/xml,application/xml,application/json
      # 最小压缩值
      min-request-size: 2048
    response:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
